/**
 * The link-preview metadata: what a chat app draws when one of this origin's URLs
 * is pasted into it.
 *
 * Lives beside vite.config.ts rather than in src/ because it is build input, not
 * app code -- nothing in the bundle imports it. tsconfig.node.json includes it for
 * the same reason it includes vite.config.ts and tests/.
 *
 * ## Why this is a file and not just tags in index.html
 *
 * The app is a client-rendered SPA served as static files by nginx, so a crawler
 * gets whatever index.html says and nothing React would have rendered: every
 * unfurler that matters (Slack, WhatsApp, iMessage, Discord, Facebook, X) reads
 * the HTML and runs no script. One index.html therefore means one preview for
 * every URL on the origin -- including the two that are *only ever* pasted to
 * somebody else, `/join/<code>` and `/invite/<code>`.
 *
 * So index.html carries a marked block of tags (see `MARKER_START`) and the Vite
 * plugin in vite.config.ts stamps out two more copies of the built document with
 * that block replaced. nginx serves those copies for the two invite prefixes. The
 * cost is two ~3 KiB HTML files and four lines of nginx; the SPA is unaffected,
 * because a variant differs from index.html only inside the block -- same bundle,
 * same theme script, and React still reads the real path out of the URL bar.
 *
 * ## What is deliberately *not* here
 *
 * **Per-code previews.** Rendering "Join the Smiths' weekly shop" would mean a
 * server that reads the code, calls the API on another origin, and renders HTML,
 * which is a service this origin does not have. It would also be a bad idea if it
 * were free: an account invite code is a JWT naming one person's email address,
 * and an unfurl is fetched by whatever link-scraper the recipient's chat app runs
 * and cached on its servers. A per-route card says what the link *is* without
 * putting anything about a household or a person into somebody else's cache.
 *
 * **twitter:title, twitter:description and twitter:image.** X's crawler falls back
 * to the og:* equivalents for all three, and has since the cards spec was written;
 * only `twitter:card` has no Open Graph counterpart. Duplicating the other three
 * is three more strings to keep in step for no behaviour.
 */

/** The public origin. og:image and og:url must be absolute -- a relative one is dropped. */
export const ORIGIN = 'https://grocery.teddy.fyi'

/** Generated by icons/build-icons.py from the same mark as the launcher icons. */
const CARD_IMAGE = {
  url: `${ORIGIN}/og-image.png`,
  width: 1200,
  height: 630,
  alt: 'A paper grocery bag full of shopping, with a green tick across it.',
}

export type SocialCard = {
  /** The document this card is stamped into, relative to the build output. */
  file: string
  /** <title>, og:title, and what a preview shows in bold. */
  title: string
  /** meta description and og:description. */
  description: string
  /**
   * The canonical absolute URL, or null for a route whose URL carries a one-use
   * code. Omitting og:url leaves the unfurler showing the link that was actually
   * pasted, which is the right one; naming a canonical for a code-bearing path
   * would be claiming every invite is a duplicate of one page.
   */
  url: string | null
  /** False adds `noindex`: a live invite has no business in a search index. */
  indexable: boolean
}

export const DEFAULT_CARD: SocialCard = {
  file: 'index.html',
  title: 'Teddy Grocery',
  description:
    "A grocery list the whole house shares. Add things at home, tick them off in the shop, and it keeps working when the signal doesn't.",
  url: `${ORIGIN}/`,
  indexable: true,
}

/**
 * The routes that get their own document. Both are links one person sends to
 * another, which is the whole reason a preview is worth anything here.
 *
 * `/help` and `/link` are public too and deliberately not on this list: they are
 * pages about the app, so the site-wide card already describes them correctly.
 */
export const ROUTE_CARDS: SocialCard[] = [
  {
    file: 'join.html',
    title: 'Join a shared grocery list',
    description:
      'Someone has shared their grocery list with you on Teddy Grocery. Open this link to sign in and start adding to it.',
    url: null,
    indexable: false,
  },
  {
    file: 'invite.html',
    title: 'Your invitation to Teddy Grocery',
    description:
      'You have been invited to Teddy Grocery, a shared grocery list for the whole house. Open this link to sign in and set up your account.',
    url: null,
    indexable: false,
  },
]

export const MARKER_START = '<!-- social-card:start -->'
export const MARKER_END = '<!-- social-card:end -->'

/** HTML-escape a value going into an attribute. The copy above contains apostrophes. */
function attr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/** The block of tags for one card, indented to sit where the markers are. */
export function renderSocialCard(card: SocialCard): string {
  const tags: string[] = [
    `<title>${attr(card.title)}</title>`,
    `<meta name="description" content="${attr(card.description)}" />`,
  ]

  if (!card.indexable) {
    tags.push('<meta name="robots" content="noindex" />')
  }
  if (card.url) {
    tags.push(`<link rel="canonical" href="${attr(card.url)}" />`, `<meta property="og:url" content="${attr(card.url)}" />`)
  }

  tags.push(
    '<meta property="og:type" content="website" />',
    `<meta property="og:site_name" content="${attr(DEFAULT_CARD.title)}" />`,
    `<meta property="og:title" content="${attr(card.title)}" />`,
    `<meta property="og:description" content="${attr(card.description)}" />`,
    '<meta property="og:locale" content="en_GB" />',
    `<meta property="og:image" content="${CARD_IMAGE.url}" />`,
    '<meta property="og:image:type" content="image/png" />',
    `<meta property="og:image:width" content="${CARD_IMAGE.width}" />`,
    `<meta property="og:image:height" content="${CARD_IMAGE.height}" />`,
    `<meta property="og:image:alt" content="${attr(CARD_IMAGE.alt)}" />`,
    // The one Twitter tag with no og:* fallback. summary_large_image is what makes
    // X draw the 1.91:1 image above the title instead of a small square thumbnail.
    '<meta name="twitter:card" content="summary_large_image" />',
  )

  return [MARKER_START, ...tags.map(tag => `  ${tag}`), MARKER_END].join('\n  ')
}

/**
 * Replace the marked block in a document with this card's tags.
 *
 * Throws rather than silently doing nothing: a missing marker means index.html has
 * been edited and every preview on the origin has quietly gone generic, which is a
 * failure nobody would notice from looking at the app.
 */
export function applySocialCard(html: string, card: SocialCard): string {
  const start = html.indexOf(MARKER_START)
  const end = html.indexOf(MARKER_END)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`index.html has no ${MARKER_START} ... ${MARKER_END} block to put the link-preview tags in`)
  }
  return html.slice(0, start) + renderSocialCard(card) + html.slice(end + MARKER_END.length)
}
