/**
 * Service worker registration, and the two ways to turn it back off.
 *
 * The app shell is precached by `sw.js` (generated by vite-plugin-pwa at build
 * time, see vite.config.ts), which is what lets a cold launch with no signal render
 * the list instead of a browser error page. Everything in this file is about the
 * lifecycle around that, because a service worker is the one deploy that does not
 * fix itself by re-shipping: a bad one can keep serving its own broken cache to a
 * phone that never asks the network again.
 *
 * Two escape hatches, deliberately at different scopes:
 *
 *   1. **One device**, from the address bar: `https://grocery.teddy.fyi/?sw=off`
 *      unregisters every worker, deletes every cache, and *remembers* -- the flag in
 *      localStorage is what stops the next load from installing it all over again.
 *      `?sw=on` clears the flag. This is the one to reach for when a single phone is
 *      stuck and you need it working before you need to know why.
 *
 *   2. **The fleet**, from CI: build with `VITE_DISABLE_SW=true` and deploy. That
 *      swaps the generated worker for vite-plugin-pwa's self-destroying one, which
 *      unregisters itself and clears its caches on every client that picks it up.
 *      The browser fetches `sw.js` over the network rather than through the worker,
 *      and `apps/grocery/nginx.conf` serves it `no-cache`, so this reaches devices
 *      whose cached app is otherwise unreachable. See DEPLOYMENT.md.
 *
 * Update policy: a new worker installs and then *waits*. It never calls
 * `skipWaiting` on its own, so a running session is never swapped underneath itself
 * -- which matters here because a swap mid-session would throw away whatever is
 * half-typed in the add-item sheet. Taking the update over is the user's choice,
 * offered by `UpdateBanner` through `subscribeToUpdates` and `applyUpdate` below,
 * and it still happens on its own at the next cold launch if they ignore it.
 */

import { storage } from '@/utils/storage'

/** Set only by the `?sw=off` hatch above; absent is the normal state. */
const SW_DISABLED_KEY = 'grocery_sw_disabled'

const KILL_PARAM = 'sw'

/**
 * How often to ask whether a new worker has shipped.
 *
 * An installed app is launched, not loaded -- it can sit in the background for days
 * without the browser ever re-fetching sw.js on its own, which is exactly the case
 * where a deploy would otherwise never arrive. Each check is a conditional request
 * for one small file, so hourly is cheap; the visibility check below is what
 * actually catches most updates, since this app is opened rather than left open.
 */
const UPDATE_POLL_MS = 60 * 60 * 1000

/**
 * Tear down every worker and cache this origin has. Exported because it is also the
 * useful half of the `?sw=off` hatch, and because a path nobody can call is a path
 * nobody can test.
 */
export async function unregisterServiceWorkers(): Promise<void> {
  if ('serviceWorker' in navigator) {
    const registrations = await navigator.serviceWorker.getRegistrations()
    await Promise.all(registrations.map(registration => registration.unregister()))
  }

  if ('caches' in window) {
    const keys = await caches.keys()
    await Promise.all(keys.map(key => caches.delete(key)))
  }
}

/**
 * Read and consume the `?sw=` parameter.
 *
 * Returns what the URL asked for, and strips the parameter from the address bar so a
 * bookmark or a shared link does not keep re-triggering it. `null` when the parameter
 * is absent, which is every normal load.
 */
function consumeKillParam(): 'off' | 'on' | null {
  const url = new URL(window.location.href)
  const value = url.searchParams.get(KILL_PARAM)
  if (value !== 'off' && value !== 'on') return null

  url.searchParams.delete(KILL_PARAM)
  window.history.replaceState(null, '', url.pathname + url.search + url.hash)
  return value
}

export async function registerServiceWorker(): Promise<void> {
  if (!('serviceWorker' in navigator)) return

  const requested = consumeKillParam()

  if (requested === 'off') {
    storage.setItem(SW_DISABLED_KEY, 'true')
    await unregisterServiceWorkers()
    return
  }

  if (requested === 'on') {
    storage.removeItem(SW_DISABLED_KEY)
  }

  // getItem runs stored values back through JSON.parse, so the string 'true' comes
  // back as the boolean. Accept both, the way main.tsx's purge flag does.
  const disabled = storage.getItem<boolean | string>(SW_DISABLED_KEY, false)
  if (disabled === true || disabled === 'true') {
    // Belt and braces: the flag is set, so make sure nothing is actually running.
    await unregisterServiceWorkers()
    return
  }

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', { scope: '/' })
    watchForUpdates(registration)
  } catch (error) {
    // A failed registration is not a failed app -- it just means no offline launch.
    // Never let it take the page down with it.
    console.error('[PWA] Service worker registration failed:', error)
  }
}

// --------------------------------------------------------------------------------
// "A new version is ready"
//
// Three things have to line up before we say that, and the middle one is the whole
// subtlety: a worker sitting in `installed` means a new version is ready ONLY if
// something is already controlling the page. On a first-ever visit the very first
// worker also passes through `installed`, and announcing an update to someone who
// just arrived is nonsense -- they are already on the newest thing there is.
// `navigator.serviceWorker.controller` is what tells the two apart.
// --------------------------------------------------------------------------------

type UpdateListener = (updateReady: boolean) => void

const listeners = new Set<UpdateListener>()

/** The installed-and-waiting worker, once there is one. */
let waiting: ServiceWorker | null = null

/** Set the moment we ask a worker to take over, so the reload below happens once. */
let activating = false

function announce(worker: ServiceWorker | null) {
  waiting = worker
  listeners.forEach(listener => listener(worker !== null))
}

/**
 * Subscribe to "a new version is waiting". Fires immediately with the current state,
 * so a component mounting after the update was found still learns about it. Returns
 * its own unsubscribe.
 */
export function subscribeToUpdates(listener: UpdateListener): () => void {
  listeners.add(listener)
  listener(waiting !== null)
  return () => {
    listeners.delete(listener)
  }
}

/**
 * Take the waiting version over, and reload onto it.
 *
 * The worker only skips waiting when asked -- `SKIP_WAITING` is the message Workbox
 * generates a listener for, and this is the only thing that sends it. The reload is
 * driven by `controllerchange` rather than fired straight after the message, because
 * the new worker has to be in control *before* the page asks for the new bundle;
 * reloading too early just re-serves the old one from the old worker.
 */
export function applyUpdate(): void {
  if (!waiting || activating) return
  activating = true
  waiting.postMessage({ type: 'SKIP_WAITING' })
}

function watchForUpdates(registration: ServiceWorkerRegistration): void {
  // Reload exactly once, however many times controllerchange fires.
  let reloading = false
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!activating || reloading) return
    reloading = true
    window.location.reload()
  })

  // Already waiting when we registered: the update landed during a previous visit
  // and the user never took it.
  if (registration.waiting && navigator.serviceWorker.controller) {
    announce(registration.waiting)
  }

  registration.addEventListener('updatefound', () => {
    const installing = registration.installing
    if (!installing) return

    installing.addEventListener('statechange', () => {
      if (installing.state !== 'installed') return
      // The controller check: an update, or just this device's first install?
      if (navigator.serviceWorker.controller) {
        announce(installing)
      }
    })
  })

  const checkForUpdate = () => {
    // Offline this throws, and that is not worth a line in the console: it means
    // exactly what it should, which is that we will ask again later.
    registration.update().catch(() => {})
  }

  window.setInterval(checkForUpdate, UPDATE_POLL_MS)

  // The one that matters on a phone. An installed app spends most of its life
  // backgrounded, and coming back to it is the moment a deploy from yesterday
  // should be found -- long before the interval above would next fire.
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') checkForUpdate()
  })
}

/** Test seam: forget any waiting worker and every listener. */
export function resetUpdateStateForTests(): void {
  listeners.clear()
  waiting = null
  activating = false
}
