/**
 * Service worker registration, and the two ways to turn it back off.
 *
 * The app shell is precached by `sw.js` (generated by vite-plugin-pwa at build
 * time, see vite.config.ts), which is what lets a cold launch with no signal render
 * the list instead of a browser error page. Everything in this file is about the
 * lifecycle around that, because a service worker is the one deploy that does not
 * fix itself by re-shipping: a bad one can keep serving its own broken cache to a
 * phone that never asks the network again.
 *
 * Two escape hatches, deliberately at different scopes:
 *
 *   1. **One device**, from the address bar: `https://grocery.teddy.fyi/?sw=off`
 *      unregisters every worker, deletes every cache, and *remembers* -- the flag in
 *      localStorage is what stops the next load from installing it all over again.
 *      `?sw=on` clears the flag. This is the one to reach for when a single phone is
 *      stuck and you need it working before you need to know why.
 *
 *   2. **The fleet**, from CI: build with `VITE_DISABLE_SW=true` and deploy. That
 *      swaps the generated worker for vite-plugin-pwa's self-destroying one, which
 *      unregisters itself and clears its caches on every client that picks it up.
 *      The browser fetches `sw.js` over the network rather than through the worker,
 *      and `apps/grocery/nginx.conf` serves it `no-cache`, so this reaches devices
 *      whose cached app is otherwise unreachable. See DEPLOYMENT.md.
 *
 * Update policy is deliberately the same as the HTTP caching it joins: a new worker
 * installs, waits, and takes over on the next cold launch. No `skipWaiting`, so a
 * running session is never swapped underneath itself. An in-app "update available"
 * prompt is a separate piece of work (Option B in docs/deployment-options.md).
 */

import { storage } from '@/utils/storage'

/** Set only by the `?sw=off` hatch above; absent is the normal state. */
const SW_DISABLED_KEY = 'grocery_sw_disabled'

const KILL_PARAM = 'sw'

/**
 * Tear down every worker and cache this origin has. Exported because it is also the
 * useful half of the `?sw=off` hatch, and because a path nobody can call is a path
 * nobody can test.
 */
export async function unregisterServiceWorkers(): Promise<void> {
  if ('serviceWorker' in navigator) {
    const registrations = await navigator.serviceWorker.getRegistrations()
    await Promise.all(registrations.map(registration => registration.unregister()))
  }

  if ('caches' in window) {
    const keys = await caches.keys()
    await Promise.all(keys.map(key => caches.delete(key)))
  }
}

/**
 * Read and consume the `?sw=` parameter.
 *
 * Returns what the URL asked for, and strips the parameter from the address bar so a
 * bookmark or a shared link does not keep re-triggering it. `null` when the parameter
 * is absent, which is every normal load.
 */
function consumeKillParam(): 'off' | 'on' | null {
  const url = new URL(window.location.href)
  const value = url.searchParams.get(KILL_PARAM)
  if (value !== 'off' && value !== 'on') return null

  url.searchParams.delete(KILL_PARAM)
  window.history.replaceState(null, '', url.pathname + url.search + url.hash)
  return value
}

export async function registerServiceWorker(): Promise<void> {
  if (!('serviceWorker' in navigator)) return

  const requested = consumeKillParam()

  if (requested === 'off') {
    storage.setItem(SW_DISABLED_KEY, 'true')
    await unregisterServiceWorkers()
    return
  }

  if (requested === 'on') {
    storage.removeItem(SW_DISABLED_KEY)
  }

  // getItem runs stored values back through JSON.parse, so the string 'true' comes
  // back as the boolean. Accept both, the way main.tsx's purge flag does.
  const disabled = storage.getItem<boolean | string>(SW_DISABLED_KEY, false)
  if (disabled === true || disabled === 'true') {
    // Belt and braces: the flag is set, so make sure nothing is actually running.
    await unregisterServiceWorkers()
    return
  }

  try {
    await navigator.serviceWorker.register('/sw.js', { scope: '/' })
  } catch (error) {
    // A failed registration is not a failed app -- it just means no offline launch.
    // Never let it take the page down with it.
    console.error('[PWA] Service worker registration failed:', error)
  }
}
